import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

print('=' * 60)
print('Deep Adaptive AEC - Quick Start')
print('=' * 60)
print()

print('Step 1: Installing dependencies...')
print('-' * 60)
print('Please run: pip install -r requirements.txt')
print()

print('Step 2: Training the model...')
print('-' * 60)
print('To train with default settings:')
print('  python train.py --epochs 30 --train_samples 500 --val_samples 50')
print()
print('This will train for 30 epochs with synthetic data.')
print('Checkpoints will be saved in the "checkpoints" directory.')
print()

print('Step 3: Running inference...')
print('-' * 60)
print('After training, run inference with:')
print('  python infer.py --checkpoint checkpoints/best_model.pth --plot')
print()
print('This will generate test audio, process it with the model,')
print('and save the results in the "output" directory.')
print()

print('=' * 60)
print('Project Structure:')
print('=' * 60)
print()
print('models/')
print('  - dnn_module.py: LSTM-based DNN for nonlinear reference estimation')
print('  - nlms_module.py: Differentiable NLMS adaptive filter')
print('  - deep_adaptive_aec.py: Full Deep Adaptive AEC model')
print()
print('utils/')
print('  - signal_processing.py: STFT/ISTFT and signal processing utilities')
print('  - metrics.py: Evaluation metrics (ERLE, SDR, PESQ, STOI)')
print()
print('data/')
print('  - dataset.py: Synthetic AEC dataset generator')
print()
print('training/')
print('  - trainer.py: Training loop with checkpointing')
print()
print('=' * 60)
print('Key Features:')
print('=' * 60)
print('  - End-to-end differentiable NLMS adaptive filter')
print('  - LSTM-based DNN for nonlinear reference estimation')
print('  - Joint echo and noise reduction mode')
print('  - Synthetic data generator for training')
print('  - Multiple evaluation metrics (ERLE, SDR, PESQ, STOI)')
print('  - Visualization of waveforms and spectrograms')
print()
print('=' * 60)
print('Ready to go!')
print('=' * 60)